name: CI/CD for Koha Plugin Packaging

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package Plugin
      run: zip -r llmsearch.kpz Koha

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: llmsearch-plugin
        path: llmsearch.kpz
